language: node_js
node_js:
  - node
sudo: false
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn install && yarn clean

jobs:
  include:
    - stage: build
      env:
        - NODE_ENV=PRODUCTION
      script: yarn build
    - stage: test
      env:
        - NODE_ENV=TEST
      script: yarn test
